#!/bin/bash

echo "🎵 Adding Romantic Music to Your Gallery"
echo "========================================"

echo ""
echo "📁 Current music file:"
ls -la public/romantic-music.mp3

echo ""
echo "🎵 To add your own romantic music:"
echo ""
echo "1. Find a romantic song you love (MP3 format)"
echo "2. Copy it to the public folder:"
echo "   cp /path/to/your/song.mp3 public/romantic-music.mp3"
echo ""
echo "3. Or drag and drop your song file to:"
echo "   $(pwd)/public/romantic-music.mp3"
echo ""
echo "💡 Recommended songs:"
echo "   - Perfect by Ed Sheeran"
echo "   - All of Me by John Legend"
echo "   - A Thousand Years by Christina Perri"
echo "   - Can't Help Falling in Love by Elvis Presley"
echo "   - Any instrumental romantic music"
echo ""
echo "🎧 The music will:"
echo "   - Play at 20% volume (subtle background)"
echo "   - Loop automatically"
echo "   - Be controlled by the play/pause button in gallery"
echo ""
echo "✨ Your romantic gallery will be complete!" 